packages:
  - "packages/*"
  - "apps/*"

minimumReleaseAge: 0

publicHoistPattern:
  - "@types/*"

injectWorkspacePackages: true
strictStorePkgContentCheck: false
forceLegacyDeploy: true

overrides:
  "@types/react": "19.2.15"
  "@types/react-dom": "19.2.3"
  react: "19.2.6"
  react-dom: "19.2.6"

updateConfig:
  ignoreDependencies:
    - eslint
    - "*eslint*"

onlyBuiltDependencies:
  - "@swc/core"
  - core-js
  - esbuild
  - fsevents
  - husky
  - leveldown
  - puppeteer

allowBuilds:
  core-js: true
  esbuild: true
  fsevents: true
  husky: true
  puppeteer: true
