
   
name: 'Get Vercel Preview URL'
description: "Get Vercel Deploy Preview to complete. Requires to be run on pull_request."
branding:
  icon: "clock"
  color: "blue"
inputs:
  token:
    description: "The Github Secret"
    required: true
  max_timeout:
    description: "The max time to run the action"
    required: false
  environment:
    description: "The name of the environment that was deployed to (e.g., staging or production)"
    required: false
  allow_inactive:
    description: "Use the most recent inactive deployment (previously deployed preview) associated with the pull request if no new deployment is available."
    required: false
  check_interval:
    description: "How often (in seconds) should we make the HTTP request checking to see if the deployment is available?"
    default: '2'
    required: false
outputs:
  url:
    description: "The fully qualified deploy preview URL"
runs:
  using: "node12"
  main: "index.js"