version: '3'

services:
  server:
    image: website_server
    environment:
      PORT: 3000
      NODE_ENV: production
    command: npm serve
    restart: always

  nginx:
    image: ngingx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /root/nginx:/etc/nginx
      - /root/ssl:/etc/nginx/ssl/
    command: nginx -c /etc/nginx/nginx.conf -g "daemon off;"
    restart: always
