name: Build and deploy

on: [ push, pull_request ]

jobs:
  build:
    environment: CI
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    name: build and deploy to aws lambda
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.6.12

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'pnpm'

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Install Dependencies
        run: pnpm i

      - name: Build App
        run: pnpm build

      - name: Deploy app to staging
        if: github.ref == 'refs/heads/main'
        working-directory: apps/frontendsupport
        run: pnpm arc deploy --staging
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy app to production
        if: startsWith(github.ref, 'refs/tags/v')
        working-directory: apps/frontendsupport
        run: pnpm arc deploy --production
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}