name: Build and deploy

on: [ push, pull_request ]

jobs:
  build:
    environment: CI
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    name: build and deploy to aws lambda
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.6.12

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'pnpm'

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Install Dependencies
        run: pnpm i

      - name: Build App
        run: pnpm build

      - name: Deploy app to staging
        if: github.ref == 'refs/heads/main'
        working-directory: apps/frontendsupport
        run: pnpm arc deploy --staging -v --prune
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy app to production
        if: startsWith(github.ref, 'refs/tags/v')
        working-directory: apps/frontendsupport
        run: pnpm arc deploy --production -v --prune
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Invalidate cache staging
        if: github.ref == 'refs/heads/main'
        uses: imehedi/actions-awscli-v2@latest
        with:
            args: cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_STAGING_ID }} --paths '/*' --no-cli-pager
            env:
              AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
              AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              AWS_DEFAULT_REGION: "us-east-1"

      - name: Invalidate cache production
        if: startsWith(github.ref, 'refs/tags/v')
        uses: imehedi/actions-awscli-v2@latest
        with:
            args: cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_PRODUCTION_ID }} --paths '/*' --no-cli-pager
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: "us-east-1"

      - name: WebPageTest Staging
        if: github.ref == 'refs/heads/main'
        uses: WPO-Foundation/webpagetest-github-action@main
        with:
          apiKey: ${{ secrets.WPT_API_KEY }}
          urls: |
            https://staging.frontendrescue.com/
            https://staging.frontendrescue.com/posts/2023-07-28-session-storage-playwright
          label: 'GitHub Action Test'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: WebPageTest Production
        if: startsWith(github.ref, 'refs/tags/v')
        uses: WPO-Foundation/webpagetest-github-action@main
        with:
          apiKey: ${{ secrets.WPT_API_KEY }}
          urls: |
            https://frontendrescue.com/
            https://frontendrescue.com/posts/2023-07-28-session-storage-playwright
          label: 'GitHub Action Test'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}