name: Changeset

on:
  push:
    branches:
      - main

jobs:
  create-release-pr:
    name: Create Changeset PR
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set yarn berry
      run: yarn set version berry
    - name: Install Dependencies
      run: yarn install
    - name: Create Release Pull Request
      uses: changesets/action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
