name: Changeset

on:
  push:
    branches:
      - main

jobs:
  create-release-pr:
    name: Create Changeset PR
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.32.6
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run:  pnpm i --no-frozen-lockfilepnpm i
    - name: Create Release Pull Request
      uses: changesets/action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
