name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Publish & Deploy
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.30.0

      - name: Checkout Repo
        uses: actions/checkout@main
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js 16.x
        uses: actions/setup-node@main
        with:
          node-version: 16.x
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm i

      - name: Create release PR or publish to npm
        uses: changesets/action@c2918239208f2162b9d27a87f491375c51592434
        with:
          version: pnpm run version
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
