name: Release

on:
  push:
    branches:
      - main

env:
  HUSKY: 0  # Bypass husky commit hook for CI

jobs:
  release:
      # prevents this action from running on forks
    if: github.repository == 'dagda1/cuttingedge'
    name: Publish & Deploy
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.32.7

      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'pnpm'


      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            email=paul.cowan@cutting.scot
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install Dependencies
        run: pnpm install
      
      - name: Create PR or Publish release
        id: changesets
        uses: changesets/action@v1
        with:
          # Custom versioning script in package.json
          version: pnpm ci:version
          # Custom versioning script in package.json
          publish: pnpm release
          # Messages
          commit: "chore: version packages"
          title: "Version Packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}