name: Release

on:
  push:
    branches:
      - main

env:
  PNPM_CACHE_FOLDER: .pnpm-store
  HUSKY: 0  # Bypass husky commit hook for CI

jobs:
  version:
    timeout-minutes: 8
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v3
        with:          
          fetch-depth: 0

      - name: setup caching
        uses: actions/cache@v2
        with:
          path: ${{ env.PNPM_CACHE_FOLDER }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.32.6

      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'pnpm'

      - name: Set up NPM credentials
        run: |
          cat << EOF > "$HOME/.npmrc"
            email=paul.cowan@cutting.scot
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF

        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}          

      - name: setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - run: pnpm install

      - name: Create versions PR & prepare publish
        id: changesets
        uses: changesets/action@v1
        if: github.ref == 'refs/heads/main'
        with:
          # Custom versioning script in package.json
          version: pnpm ci:version
          # Custom versioning script in package.json
          publish: pnpm ci:publish
          # Messages
          commit: 'chore(deploy): Release'
          title: 'chore(deploy): Release'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  