name: Release

on:
  push:
    branches:
      - main

env:
  HUSKY: 0  # Bypass husky commit hook for CI

jobs:
  release:
    name: Publish & Deploy
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.32.7

      - name: Checkout Repo
        uses: actions/checkout@main
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js 16.x
        uses: actions/setup-node@main
        with:
          node-version: 16.x
          cache: 'pnpm'


      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            email=paul.cowan@cutting.scot
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install Dependencies
        run: pnpm i
      
      - name: Create PR or Publish release
        id: changesets
        uses: changesets/action@master
        with:
          # Custom versioning script in package.json
          version: pnpm ci:version
          # Custom versioning script in package.json
          publish: pnpm ci:publish
          # Messages
          commit: 'chore(deploy): Release'
          title: 'chore(deploy): Release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}