name: Second Workflow

on:
  repository_dispatch:
    types: [trigger-webpage-test-for-frontendsupport]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: WebPageTest Staging
        uses: WPO-Foundation/webpagetest-github-action@main
        with:
          apiKey: ${{ secrets.WPT_API_KEY }}
          urls: |
            https://staging.frontendrescue.com/
            https://staging.frontendrescue.com/posts/2023-07-28-session-storage-playwright
          label: 'GitHub Action Test'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: WebPageTest Production
        if: startsWith(github.ref, 'refs/tags/v')
        uses: WPO-Foundation/webpagetest-github-action@main
        with:
          apiKey: ${{ secrets.WPT_API_KEY }}
          urls: |
            https://frontendrescue.com/
            https://frontendrescue.com/posts/2023-07-28-session-storage-playwright
          label: 'GitHub Action Test'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}